name: Build and Deploy to K3s

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: self-hosted
    outputs: 
      tag: ${{ steps.date.outputs.tag }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: registry.wattega.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Get current date as tag
        id: date # <-- Important: L'identificador del pas
        run: |
          TAG=$(date +'%Y%m%d%H%M%S')
          echo "TAG=${TAG}" >> $GITHUB_ENV
          echo "tag=${TAG}" >> $GITHUB_OUTPUT # <-- NOU: Declarem la sortida

      - name: Build and push Docker image
        run: |
          make push TAG=${{ env.TAG }}
        env:
          REGISTRY_URL: ${{ secrets.REGISTRY_URL }}

  deploy-to-k3s:
    runs-on: self-hosted
    needs: build-and-push # Aquest job depèn de l'anterior i de la seva sortida
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config
      
      
      - name: Deploy to K3s cluster
        run: |
          # Utilitzem l'etiqueta que ens ve del job anterior
          make deploy TAG=${{ needs.build-and-push.outputs.tag }}
        env:
          REGISTRY_URL: ${{ secrets.REGISTRY_URL }}