name: Build & Deploy RAG Container

on:
  push:
    branches:
      - main

env:
  # --- Defineix aquí les variables per a aquest projecte ---
  IMAGE_TAG: registry.wattega.com/test/llm-rag-app:latest # Imatge base (s'afegirà un tag dinàmic)
  APP_NAME: llm-rag-app
  APP_PORT: 8000 # Ha de coincidir amb el port exposat al Dockerfile

jobs:
  build:
    name: Build and Push Docker Image
    runs-on: [self-hosted]
    outputs:
      tag: ${{ steps.tagger.outputs.tag }} # Exportem el tag per al següent job
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate image tag
        id: tagger
        run: |
          TAG=$(date +'%Y%m%d%H%M%S')
          echo "tag=${TAG}" >> $GITHUB_OUTPUT

      - name: Login to private registry
        uses: docker/login-action@v3
        with:
          registry: registry.wattega.com
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            registry.wattega.com/test/llm-rag-app:${{ steps.tagger.outputs.tag }}
            registry.wattega.com/test/llm-rag-app:latest
  
  deploy:
    name: Deploy to K3s
    needs: [build]
    runs-on: [self-hosted]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Substitute variables and deploy
        # Passem el tag del job anterior com a variable d'entorn
        env:
          IMAGE_TAG: registry.wattega.com/test/llm-rag-app:${{ needs.build.outputs.tag }}
          APP_NAME: ${{ env.APP_NAME }}
          APP_PORT: ${{ env.APP_PORT }}
        run: |
          echo "--- Generant fitxers de desplegament des de les plantilles ---"
          envsubst < ./k3s/app-deployment.yaml.template > ./k3s/app-deployment.yaml
          envsubst < ./k3s/app-service.yaml.template > ./k3s/app-service.yaml
          envsubst < ./k3s/app-ingress.yaml.template > ./k3s/app-ingress.yaml

          echo "--- Desplegant a K3s ---"
          # Apliquem tots els fitxers de la carpeta, inclosos els generats i el pv-pvc.yaml
          kubectl apply -f ./k3s/

          echo "--- Verificant l'estat del desplegament ---"
          kubectl rollout status deployment/${{ env.APP_NAME }}